name: .NET Web App

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore MyAmazingWeb
    - name: Build
      run: dotnet build --no-restore MyAmazingWeb
    - name: Test
      run: dotnet test --no-build --verbosity normal MyAmazingWeb
    - name: Publish
      run: dotnet publish -c Release -o dotnetcorewebapp MyAmazingWeb 
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: myamazingwebapp
        publish-profile: ${{ secrets.MYAMAZINGWEBAPP_PUBLISH_PROFILE }}
        package: './dotnetcorewebapp/'
