name: .NET Web App

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore MyAmazingWeb
    - name: Build
      run: dotnet build --no-restore MyAmazingWeb
    - name: Test
      run: dotnet test --no-build --verbosity normal MyAmazingWeb
    - name: Publish
      run: dotnet publish -c Release -o dotnetcorewebapp MyAmazingWeb
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: webapp
        path: dotnetcorewebapp
    
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: webapp
        path: dotnetcorewebapp
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    - name: 'Run Azure webapp deploy action using federated credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ActionsInActionWebApp
        package: './dotnetcorewebapp/'
