name: Add Label on Issue

on:
  issues:
    types: [opened]

jobs:
  apply-label-on-bug:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.issue.title, '#bug') }}
    steps:
      - uses: actions/github-script@v8
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Triage']
            })